kind: Service
apiVersion: v1
metadata:
  name: playfab-auth
spec:
  selector:
    app: playfab-auth
  ports:
  - protocol: TCP
    name: 'http1'
    port: 80
    targetPort: 9001
  - protocol: TCP
    name: 'grpc'
    port: 4000
    targetPort: 9000
  type: LoadBalancer    # triggers a cloud native load balancer (aws alb) to be provisioned
  loadBalancerIP: "34.74.118.132" # Update - gives an IP to the cloud native load balancer
