apiVersion: v1
kind: ConfigMap
metadata:
  name: online-services-config
  selfLink: /api/v1/namespaces/default/configmaps/online-services-config
data:
  redis.connection-string: "127.0.0.1:6379"
  spatialos.project: "beta_six_magnesium_77"
  playfab.title: "B4731"
