kind: Service
apiVersion: v1
metadata:
  name: party
spec:
  selector:
    app: party
  ports:
  - protocol: TCP
    name: 'http1'
    port: 80
    targetPort: 9001
  - protocol: TCP
    name: 'grpc'
    port: 4000
    targetPort: 9000
  type: LoadBalancer
  loadBalancerIP: "{{your_party_host}}" # Update
